[package]
name = "todo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
colored = "3.0.0"
jiff = { version = "0.2.15", features = ["serde"] }
serde = {version = "1.0.219",features= ["derive"] }
serde_json = "1.0.142"
tabled = "0.20.0"
