[package]
name = "todo"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.32.3", features = ["glow", "wayland", "x11"] }
jiff = { version = "0.2.15", features = ["serde"] }
serde = {version = "1.0.219",features= ["derive"] }
serde_json = "1.0.142"
